parameters:
#    komodo_user.example.class: Komodo\UserBundle\Example

services:
#    komodo_user.example:
#        class: %komodo_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
